# Generated by Django 5.0.2 on 2024-02-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_mail_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
