# Generated by Django 4.2.10 on 2024-02-17 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0004_user_upload_folder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="upload_folder",
        ),
    ]
